// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REMOVED_FIREBASE_WEB_KEY',
    appId: '1:792530044338:web:c6f7de9f850fb48e4f50ab',
    messagingSenderId: '792530044338',
    projectId: 'sportset-d345c',
    authDomain: 'sportset-d345c.firebaseapp.com',
    storageBucket: 'sportset-d345c.firebasestorage.app',
    measurementId: 'G-TMH17VHH8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REMOVED_FIREBASE_ANDROID_KEY',
    appId: '1:792530044338:android:f214c6ab5d22e04f4f50ab',
    messagingSenderId: '792530044338',
    projectId: 'sportset-d345c',
    storageBucket: 'sportset-d345c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REMOVED_FIREBASE_IOS_KEY',
    appId: '1:792530044338:ios:5b8737a4dac752014f50ab',
    messagingSenderId: '792530044338',
    projectId: 'sportset-d345c',
    storageBucket: 'sportset-d345c.firebasestorage.app',
    iosBundleId: 'com.example.sportsetAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REMOVED_FIREBASE_IOS_KEY',
    appId: '1:792530044338:ios:5b8737a4dac752014f50ab',
    messagingSenderId: '792530044338',
    projectId: 'sportset-d345c',
    storageBucket: 'sportset-d345c.firebasestorage.app',
    iosBundleId: 'com.example.sportsetAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REMOVED_FIREBASE_WEB_KEY',
    appId: '1:792530044338:web:bd121665b2722b9b4f50ab',
    messagingSenderId: '792530044338',
    projectId: 'sportset-d345c',
    authDomain: 'sportset-d345c.firebaseapp.com',
    storageBucket: 'sportset-d345c.firebasestorage.app',
    measurementId: 'G-1Y3YVDF3XG',
  );
}
